Update

diff --git a/scripts/formatcheck b/scripts/formatcheck
--- a/scripts/formatcheck
+++ b/scripts/formatcheck
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 if [ -z "${MESON_SOURCE_ROOT}" ]; then
-    echo "[ERROR] This script can only be ran with meson!"
-    exit 1
+  echo "[ERROR] This script can only be ran with meson!"
+  exit 1
 fi
 
 cd "${MESON_SOURCE_ROOT}"
@@ -10,5 +10,5 @@ cd "${MESON_SOURCE_ROOT}"
 set -e
 files=$(scripts/get_include_files)
 for file in $files; do
-    diff $file <(clang-format -style=mozilla $file)
+  diff $file <(clang-format -style=mozilla $file)
 done
diff --git a/scripts/get_include_relative b/scripts/get_include_relative
--- a/scripts/get_include_relative
+++ b/scripts/get_include_relative
@@ -1,13 +1,13 @@
 #!/bin/bash
 
 if [ -z "${MESON_SOURCE_ROOT}" ]; then
-    echo "[ERROR] This script can only be ran with meson!"
-    exit 1
+  echo "[ERROR] This script can only be ran with meson!"
+  exit 1
 fi
 
 if [ "$#" -ne 1 ]; then
-    echo "Missing argument"
-    exit 1
+  echo "Missing argument"
+  exit 1
 fi
 
 cd "${MESON_SOURCE_ROOT}"
diff --git a/scripts/get_wrapper_files b/scripts/get_wrapper_files
--- a/scripts/get_wrapper_files
+++ b/scripts/get_wrapper_files
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 if [ -z "${MESON_SOURCE_ROOT}" ]; then
-    echo "[ERROR] This script can only be ran with meson!"
-    exit 1
+  echo "[ERROR] This script can only be ran with meson!"
+  exit 1
 fi
 
 cd "${MESON_SOURCE_ROOT}"
@@ -11,5 +11,5 @@ files=$(find extras/python -type f | grep "\(.*\.h\)\|\(.*\.cpp\)\|\(.*\.cxx\)")
 files+=" "
 files+=$(find extras/java -type f | grep "\(.*\.h\)\|\(.*\.cpp\)\|\(.*\.cxx\)")
 for file in $files; do
-    echo -n "$(realpath $file) "
+  echo -n "$(realpath $file) "
 done
diff --git a/scripts/wrap b/scripts/wrap
--- a/scripts/wrap
+++ b/scripts/wrap
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 if [ -z "${MESON_SOURCE_ROOT}" ]; then
-    echo "[ERROR] This script can only be ran with meson!"
-    exit 1
+  echo "[ERROR] This script can only be ran with meson!"
+  exit 1
 fi
 
 set -e
@@ -21,9 +21,9 @@ echo "%module btllib
 %{" > extras/java/btllib.i
 
 for file in ${include_files}; do
-    relative=$(scripts/get_include_relative ${file})
-    path="${relative}/$(basename ${file})"
-    echo "#include \"$path\"" >> extras/java/btllib.i
+  relative=$(scripts/get_include_relative ${file})
+  path="${relative}/$(basename ${file})"
+  echo "#include \"$path\"" >> extras/java/btllib.i
 done
 
 echo "%}
@@ -36,9 +36,9 @@ echo "%}
 " >> extras/java/btllib.i
 
 for file in ${include_files}; do
-    relative=$(scripts/get_include_relative ${file})
-    path="${relative}/$(basename ${file})"
-    echo "%include \"$path\"" >> extras/java/btllib.i
+  relative=$(scripts/get_include_relative ${file})
+  path="${relative}/$(basename ${file})"
+  echo "%include \"$path\"" >> extras/java/btllib.i
 done
 
 ln -sf $PWD/include extras/java/
@@ -63,9 +63,9 @@ echo "%module btllib
 " > extras/python/btllib.i
 
 for file in ${include_files}; do
-    relative=$(scripts/get_include_relative ${file})
-    path="${relative}/$(basename ${file})"
-    echo "#include \"$path\"" >> extras/python/btllib.i
+  relative=$(scripts/get_include_relative ${file})
+  path="${relative}/$(basename ${file})"
+  echo "#include \"$path\"" >> extras/python/btllib.i
 done
 
 echo "%}
@@ -85,9 +85,9 @@ echo "%}
 " >> extras/python/btllib.i
 
 for file in ${include_files}; do
-    relative=$(scripts/get_include_relative ${file})
-    path="${relative}/$(basename ${file})"
-    echo "%include \"$path\"" >> extras/python/btllib.i
+  relative=$(scripts/get_include_relative ${file})
+  path="${relative}/$(basename ${file})"
+  echo "%include \"$path\"" >> extras/python/btllib.i
 done
 
 ln -sf $PWD/include extras/python/
